//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurs4v28.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EdDelRep
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string table_name { get; set; }
        public Nullable<System.DateTime> date_update { get; set; }
        public string deistv_name { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
