//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurs4v28.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee()
        {
            this.post_otpravlenie = new HashSet<post_otpravlenie>();
            this.EdDelRep = new HashSet<EdDelRep>();
        }
    
        public int id { get; set; }
        public string emp_name { get; set; }
        public string emp_surname { get; set; }
        public string emp_otchestvo { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public int role_id { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<post_otpravlenie> post_otpravlenie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EdDelRep> EdDelRep { get; set; }
    }
}
