//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurs4v28.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class post_officeEntities2 : DbContext
    {
        public post_officeEntities2()
            : base("name=post_officeEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<popitki_vhoda> popitki_vhoda { get; set; }
        public virtual DbSet<report> report { get; set; }
        public virtual DbSet<services> services { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Sposob_otpravki> Sposob_otpravki { get; set; }
        public virtual DbSet<post_otpravlenie> post_otpravlenie { get; set; }
        public virtual DbSet<EdDelRep> EdDelRep { get; set; }
    }
}
