//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurs4v28.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class popitki_vhoda
    {
        public int id { get; set; }
        public Nullable<System.DateTime> first_popitka { get; set; }
        public Nullable<System.DateTime> last_popitka { get; set; }
        public bool isBlocked { get; set; }
        public Nullable<int> popitka_number { get; set; }
        public string pc_name { get; set; }
    }
}
