//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurs4v28.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class post_otpravlenie
    {
        public int id { get; set; }
        public int client_id { get; set; }
        public int emp_id { get; set; }
        public int service_id { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<decimal> size { get; set; }
        public string index_dostavki { get; set; }
        public Nullable<System.DateTime> date_dostavki { get; set; }
        public Nullable<decimal> full_price { get; set; }
        public int sposob_otprki_id { get; set; }
        public string address_dostavki { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<bool> isFinished { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual employee employee { get; set; }
        public virtual services services { get; set; }
        public virtual Sposob_otpravki Sposob_otpravki { get; set; }
    }
}
