//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurs4v28.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class report
    {
        public int id { get; set; }
        public string type { get; set; }
        public string period { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string dannie { get; set; }
    }
}
